#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef ALATFRAMEWORK_SWIFT_H
#define ALATFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import QuartzCore;
@import UIKit;
#endif

#import <AlatFramework/AlatFramework.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlatFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSCoder;

SWIFT_CLASS("_TtC13AlatFramework7BaseXib")
@interface BaseXib : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13AlatFramework11AccountCard")
@interface AccountCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class RegularLabel;
@class UIImageView;
@class UITextField;
@class NSString;
@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10InputField")
@interface InputField : BaseXib
@property (nonatomic, weak) IBOutlet RegularLabel * _Null_unspecified topRightLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified topRightIcon;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified textField;
@property (nonatomic, weak) IBOutlet RegularLabel * _Null_unspecified infoText;
@property (nonatomic, weak) IBOutlet RegularLabel * _Null_unspecified errorText;
@property (nonatomic) IBInspectable NSInteger numberOfCharacters;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic) IBInspectable BOOL secureTextEntry;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull info;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull titleText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull error;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull placeHolder;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull topRightPromtText;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable icon;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)prepareForInterfaceBuilder;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework15VerifiableField")
@interface VerifiableField : InputField
- (void)layoutSubviews;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
@end


SWIFT_CLASS("_TtC13AlatFramework18AccountNumberField")
@interface AccountNumberField : VerifiableField
- (void)layoutSubviews;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
@end


SWIFT_CLASS("_TtC13AlatFramework20AccountSelectorField")
@interface AccountSelectorField : InputField
@property (nonatomic) IBInspectable BOOL useAccountNumber;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11AccountView")
@interface AccountView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13AccountsModal")
@interface AccountsModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;

@interface AccountsModal (SWIFT_EXTENSION(AlatFramework)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13AlatFramework11ActionModal")
@interface ActionModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ActionModal (SWIFT_EXTENSION(AlatFramework)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework18ActionNotification")
@interface ActionNotification : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull titletext;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull subtitletext;
@property (nonatomic, strong) IBInspectable UIImage * _Nonnull displayImage;
@property (nonatomic) IBInspectable BOOL useCounter;
@property (nonatomic) IBInspectable NSInteger count;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11ActionsCard")
@interface ActionsCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework20AdminAccountCardView")
@interface AdminAccountCardView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework20AdminAccountListView")
@interface AdminAccountListView : BaseXib
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified checkBox;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework18AdminAccountsModal")
@interface AdminAccountsModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UICollectionView;
@class UICollectionViewCell;
@class UICollectionViewLayout;

@interface AdminAccountsModal (SWIFT_EXTENSION(AlatFramework)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13AlatFramework10AdvertView")
@interface AdvertView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework23AutoSizingTableViewCell")
@interface AutoSizingTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework12BankDropDown")
@interface BankDropDown : InputField
@end



SWIFT_CLASS("_TtC13AlatFramework8BankView")
@interface BankView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13AlatFramework25BeneficiaryRecipientModal")
@interface BeneficiaryRecipientModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework15BeneficiaryView")
@interface BeneficiaryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11CustomLabel")
@interface CustomLabel : UILabel
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, copy) IBInspectable NSString * _Nullable boldText;
@property (nonatomic, copy) IBInspectable NSArray<NSString *> * _Nullable boldTexts;
@property (nonatomic, copy) IBInspectable NSString * _Nullable linkText;
@property (nonatomic, copy) IBInspectable NSString * _Nullable linkText2;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework9BoldLabel")
@interface BoldLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13BorderedImage")
@interface BorderedImage : UIImageView
- (void)awakeFromNib;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11BottomModal")
@interface BottomModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework11BulletLabel")
@interface BulletLabel : UILabel
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10ButtonText")
@interface ButtonText : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nullable tagText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework11ButtonsView")
@interface ButtonsView : BaseXib
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework8Carousel")
@interface Carousel : iCarousel
@property (nonatomic) IBInspectable CGFloat spacing;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface Carousel (SWIFT_EXTENSION(AlatFramework)) <iCarouselDataSource>
- (NSInteger)numberOfItemsInCarousel:(iCarousel * _Nonnull)carousel SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)carousel:(iCarousel * _Nonnull)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView * _Nullable)view SWIFT_WARN_UNUSED_RESULT;
@end


@interface Carousel (SWIFT_EXTENSION(AlatFramework)) <iCarouselDelegate>
- (void)carouselCurrentItemIndexDidChange:(iCarousel * _Nonnull)carousel;
- (CGFloat)carousel:(iCarousel * _Nonnull)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)carouselItemWidth:(iCarousel * _Nonnull)carousel SWIFT_WARN_UNUSED_RESULT;
- (CATransform3D)carousel:(iCarousel * _Nonnull)carousel itemTransformForOffset:(CGFloat)offset baseTransform:(CATransform3D)transform SWIFT_WARN_UNUSED_RESULT;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework14CheckboxButton")
@interface CheckboxButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic) IBInspectable BOOL isChecked;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull titleText;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19CircularProgressBar")
@interface CircularProgressBar : UIView
@property (nonatomic) IBInspectable CGFloat maxValue;
@property (nonatomic) IBInspectable CGFloat currentValue;
@property (nonatomic) IBInspectable CGFloat startValue;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19ClickableLabelField")
@interface ClickableLabelField : InputField
- (void)layoutSubviews;
@end



SWIFT_CLASS("_TtC13AlatFramework17CustomPageControl")
@interface CustomPageControl : UIPageControl
@property (nonatomic) NSInteger numberOfPages;
@property (nonatomic) NSInteger currentPage;
- (void)awakeFromNib;
- (void)updateConstraints;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework7DataRow")
@interface DataRow : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull firstItem;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull secondItem;
@property (nonatomic) IBInspectable BOOL showSeperator;
@property (nonatomic) IBInspectable BOOL isTotal;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10DatePicker")
@interface DatePicker : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13DebitCardView")
@interface DebitCardView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework8DropDown")
@interface DropDown : InputField
@property (nonatomic, copy) IBInspectable NSString * _Nonnull pickerTitle;
@end


SWIFT_CLASS("_TtC13AlatFramework25DynamicCollectionViewCell")
@interface DynamicCollectionViewCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework20DynamicTableViewCell")
@interface DynamicTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework10EmailField")
@interface EmailField : InputField
@end


SWIFT_CLASS("_TtC13AlatFramework17FXBeneficiaryView")
@interface FXBeneficiaryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13FXSummaryView")
@interface FXSummaryView : BaseXib
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified amountValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified offShoreValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified comissionValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified vatValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified swiftValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified totalAmountValue;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework24FXTransactionHistoryCard")
@interface FXTransactionHistoryCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class MediumLabel;

SWIFT_CLASS("_TtC13AlatFramework23FailedNotificationModal")
@interface FailedNotificationModal : BaseXib
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contentDataView;
@property (nonatomic, weak) IBOutlet MediumLabel * _Null_unspecified dateLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13AlatFramework9FullModal")
@interface FullModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13AlatFramework24FxTransactionHistoryView")
@interface FxTransactionHistoryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework18HistoryFilterModal")
@interface HistoryFilterModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework18HorizontalCellView")
@interface HorizontalCellView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework8IDButton")
@interface IDButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework18ImageTitleSubtitle")
@interface ImageTitleSubtitle : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end



@interface InputField (SWIFT_EXTENSION(AlatFramework)) <UITextFieldDelegate>
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11ItalicLabel")
@interface ItalicLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10LightLabel")
@interface LightLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework12LoadingModal")
@interface LoadingModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11MediumLabel")
@interface MediumLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework10MoneyField")
@interface MoneyField : InputField
@property (nonatomic, copy) IBInspectable NSString * _Nullable currencySymbol;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13AlatFramework24MultipleTransferCellView")
@interface MultipleTransferCellView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13NoAccountCard")
@interface NoAccountCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework23NotificationFilterModal")
@interface NotificationFilterModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13AlatFramework11NumberField")
@interface NumberField : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10OptionView")
@interface OptionView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable optionIcon;
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic, copy) IBInspectable NSString * _Nullable descriptionText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull number;
@property (nonatomic) IBInspectable BOOL noImage;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11PaddedLabel")
@interface PaddedLabel : MediumLabel
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull background;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)drawTextInRect:(CGRect)rect;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13PasswordField")
@interface PasswordField : InputField
@end


SWIFT_CLASS("_TtC13AlatFramework16PastLoanCellView")
@interface PastLoanCellView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework17PendingActionView")
@interface PendingActionView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework22PendingTransactionView")
@interface PendingTransactionView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull title;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework10PhoneField")
@interface PhoneField : InputField
@end


SWIFT_CLASS("_TtC13AlatFramework11PickerModal")
@interface PickerModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end



@interface PickerModal (SWIFT_EXTENSION(AlatFramework)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13AlatFramework8PinField")
@interface PinField : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11PlainButton")
@interface PlainButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class SemiLabel;

SWIFT_CLASS("_TtC13AlatFramework23PreApprovedLoanCellView")
@interface PreApprovedLoanCellView : BaseXib
@property (nonatomic, weak) IBOutlet SemiLabel * _Null_unspecified loanAmountLabel;
@property (nonatomic, weak) IBOutlet SemiLabel * _Null_unspecified tenorLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19PreApprovedLoanView")
@interface PreApprovedLoanView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework21PrimaryBorderedButton")
@interface PrimaryBorderedButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13PrimaryButton")
@interface PrimaryButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework15QuickActionView")
@interface QuickActionView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework18RecipientListModal")
@interface RecipientListModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface RecipientListModal (SWIFT_EXTENSION(AlatFramework)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework12RegularLabel")
@interface RegularLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11SearchField")
@interface SearchField : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework17SegmentOptionView")
@interface SegmentOptionView : BaseXib
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified segmentImage;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic) IBInspectable BOOL isSelected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework31SegmentedOptionWithoutImageView")
@interface SegmentedOptionWithoutImageView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic) IBInspectable BOOL isSelected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework14SelectableCard")
@interface SelectableCard : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework9SemiLabel")
@interface SemiLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework16SingleDetailView")
@interface SingleDetailView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework14SoftTokenModal")
@interface SoftTokenModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11SummaryView")
@interface SummaryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSTextStorage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13TextViewField")
@interface TextViewField : InputField <NSTextStorageDelegate>
- (void)textStorage:(NSTextStorage * _Nonnull)textStorage didProcessEditing:(NSTextStorageEditActions)editedMask range:(NSRange)editedRange changeInLength:(NSInteger)delta;
@end

@class NSLayoutManager;

@interface TextViewField (SWIFT_EXTENSION(AlatFramework)) <NSLayoutManagerDelegate>
- (CGFloat)layoutManager:(NSLayoutManager * _Nonnull)layoutManager lineSpacingAfterGlyphAtIndex:(NSInteger)glyphIndex withProposedLineFragmentRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13AlatFramework5Toast")
@interface Toast : UILabel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13AlatFramework22TransactionHistoryCard")
@interface TransactionHistoryCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end








IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework12UploadButton")
@interface UploadButton : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull title;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull info;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull buttonText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull errorText;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)prepareForInterfaceBuilder;
@end

@class UIImagePickerController;
@class UIDocumentPickerViewController;
@class NSURL;

@interface UploadButton (SWIFT_EXTENSION(AlatFramework)) <UIDocumentPickerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19WhiteBorderedButton")
@interface WhiteBorderedButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11WhiteButton")
@interface WhiteButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
#ifndef ALATFRAMEWORK_SWIFT_H
#define ALATFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wduplicate-method-match"
#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT noexcept
#endif
#else
#if !defined(SWIFT_NOEXCEPT)
# define SWIFT_NOEXCEPT 
#endif
#endif
#if defined(__cplusplus)
#if !defined(SWIFT_CXX_INT_DEFINED)
#define SWIFT_CXX_INT_DEFINED
namespace swift {
using Int = ptrdiff_t;
using UInt = size_t;
}
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import QuartzCore;
@import UIKit;
#endif

#import <AlatFramework/AlatFramework.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlatFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSCoder;

SWIFT_CLASS("_TtC13AlatFramework7BaseXib")
@interface BaseXib : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13AlatFramework11AccountCard")
@interface AccountCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class RegularLabel;
@class UIImageView;
@class UITextField;
@class NSString;
@class UIImage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10InputField")
@interface InputField : BaseXib
@property (nonatomic, weak) IBOutlet RegularLabel * _Null_unspecified topRightLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified topRightIcon;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified textField;
@property (nonatomic, weak) IBOutlet RegularLabel * _Null_unspecified infoText;
@property (nonatomic, weak) IBOutlet RegularLabel * _Null_unspecified errorText;
@property (nonatomic) IBInspectable NSInteger numberOfCharacters;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic) IBInspectable BOOL secureTextEntry;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull info;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull titleText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull error;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull placeHolder;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull topRightPromtText;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable icon;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)prepareForInterfaceBuilder;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework15VerifiableField")
@interface VerifiableField : InputField
- (void)layoutSubviews;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
@end


SWIFT_CLASS("_TtC13AlatFramework18AccountNumberField")
@interface AccountNumberField : VerifiableField
- (void)layoutSubviews;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
@end


SWIFT_CLASS("_TtC13AlatFramework20AccountSelectorField")
@interface AccountSelectorField : InputField
@property (nonatomic) IBInspectable BOOL useAccountNumber;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11AccountView")
@interface AccountView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13AccountsModal")
@interface AccountsModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;

@interface AccountsModal (SWIFT_EXTENSION(AlatFramework)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13AlatFramework11ActionModal")
@interface ActionModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ActionModal (SWIFT_EXTENSION(AlatFramework)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework18ActionNotification")
@interface ActionNotification : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull titletext;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull subtitletext;
@property (nonatomic, strong) IBInspectable UIImage * _Nonnull displayImage;
@property (nonatomic) IBInspectable BOOL useCounter;
@property (nonatomic) IBInspectable NSInteger count;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11ActionsCard")
@interface ActionsCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework20AdminAccountCardView")
@interface AdminAccountCardView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework20AdminAccountListView")
@interface AdminAccountListView : BaseXib
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified checkBox;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework18AdminAccountsModal")
@interface AdminAccountsModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UICollectionView;
@class UICollectionViewCell;
@class UICollectionViewLayout;

@interface AdminAccountsModal (SWIFT_EXTENSION(AlatFramework)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13AlatFramework10AdvertView")
@interface AdvertView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework23AutoSizingTableViewCell")
@interface AutoSizingTableViewCell : UITableViewCell
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework12BankDropDown")
@interface BankDropDown : InputField
@end



SWIFT_CLASS("_TtC13AlatFramework8BankView")
@interface BankView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13AlatFramework25BeneficiaryRecipientModal")
@interface BeneficiaryRecipientModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework15BeneficiaryView")
@interface BeneficiaryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11CustomLabel")
@interface CustomLabel : UILabel
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, copy) IBInspectable NSString * _Nullable boldText;
@property (nonatomic, copy) IBInspectable NSArray<NSString *> * _Nullable boldTexts;
@property (nonatomic, copy) IBInspectable NSString * _Nullable linkText;
@property (nonatomic, copy) IBInspectable NSString * _Nullable linkText2;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework9BoldLabel")
@interface BoldLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13BorderedImage")
@interface BorderedImage : UIImageView
- (void)awakeFromNib;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11BottomModal")
@interface BottomModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework11BulletLabel")
@interface BulletLabel : UILabel
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10ButtonText")
@interface ButtonText : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nullable tagText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework11ButtonsView")
@interface ButtonsView : BaseXib
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework8Carousel")
@interface Carousel : iCarousel
@property (nonatomic) IBInspectable CGFloat spacing;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface Carousel (SWIFT_EXTENSION(AlatFramework)) <iCarouselDataSource>
- (NSInteger)numberOfItemsInCarousel:(iCarousel * _Nonnull)carousel SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)carousel:(iCarousel * _Nonnull)carousel viewForItemAtIndex:(NSInteger)index reusingView:(UIView * _Nullable)view SWIFT_WARN_UNUSED_RESULT;
@end


@interface Carousel (SWIFT_EXTENSION(AlatFramework)) <iCarouselDelegate>
- (void)carouselCurrentItemIndexDidChange:(iCarousel * _Nonnull)carousel;
- (CGFloat)carousel:(iCarousel * _Nonnull)carousel valueForOption:(iCarouselOption)option withDefault:(CGFloat)value SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)carouselItemWidth:(iCarousel * _Nonnull)carousel SWIFT_WARN_UNUSED_RESULT;
- (CATransform3D)carousel:(iCarousel * _Nonnull)carousel itemTransformForOffset:(CGFloat)offset baseTransform:(CATransform3D)transform SWIFT_WARN_UNUSED_RESULT;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework14CheckboxButton")
@interface CheckboxButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic) IBInspectable BOOL isChecked;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull titleText;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19CircularProgressBar")
@interface CircularProgressBar : UIView
@property (nonatomic) IBInspectable CGFloat maxValue;
@property (nonatomic) IBInspectable CGFloat currentValue;
@property (nonatomic) IBInspectable CGFloat startValue;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19ClickableLabelField")
@interface ClickableLabelField : InputField
- (void)layoutSubviews;
@end



SWIFT_CLASS("_TtC13AlatFramework17CustomPageControl")
@interface CustomPageControl : UIPageControl
@property (nonatomic) NSInteger numberOfPages;
@property (nonatomic) NSInteger currentPage;
- (void)awakeFromNib;
- (void)updateConstraints;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework7DataRow")
@interface DataRow : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull firstItem;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull secondItem;
@property (nonatomic) IBInspectable BOOL showSeperator;
@property (nonatomic) IBInspectable BOOL isTotal;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10DatePicker")
@interface DatePicker : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13DebitCardView")
@interface DebitCardView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework8DropDown")
@interface DropDown : InputField
@property (nonatomic, copy) IBInspectable NSString * _Nonnull pickerTitle;
@end


SWIFT_CLASS("_TtC13AlatFramework25DynamicCollectionViewCell")
@interface DynamicCollectionViewCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework20DynamicTableViewCell")
@interface DynamicTableViewCell : UITableViewCell
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework10EmailField")
@interface EmailField : InputField
@end


SWIFT_CLASS("_TtC13AlatFramework17FXBeneficiaryView")
@interface FXBeneficiaryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13FXSummaryView")
@interface FXSummaryView : BaseXib
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contentView;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified amountValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified offShoreValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified comissionValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified vatValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified swiftValue;
@property (nonatomic, weak) IBOutlet BoldLabel * _Null_unspecified totalAmountValue;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework24FXTransactionHistoryCard")
@interface FXTransactionHistoryCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class MediumLabel;

SWIFT_CLASS("_TtC13AlatFramework23FailedNotificationModal")
@interface FailedNotificationModal : BaseXib
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contentDataView;
@property (nonatomic, weak) IBOutlet MediumLabel * _Null_unspecified dateLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13AlatFramework9FullModal")
@interface FullModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13AlatFramework24FxTransactionHistoryView")
@interface FxTransactionHistoryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework18HistoryFilterModal")
@interface HistoryFilterModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework18HorizontalCellView")
@interface HorizontalCellView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework8IDButton")
@interface IDButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework18ImageTitleSubtitle")
@interface ImageTitleSubtitle : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end



@interface InputField (SWIFT_EXTENSION(AlatFramework)) <UITextFieldDelegate>
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (void)textFieldDidEndEditing:(UITextField * _Nonnull)textField;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11ItalicLabel")
@interface ItalicLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10LightLabel")
@interface LightLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework12LoadingModal")
@interface LoadingModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11MediumLabel")
@interface MediumLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework10MoneyField")
@interface MoneyField : InputField
@property (nonatomic, copy) IBInspectable NSString * _Nullable currencySymbol;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13AlatFramework24MultipleTransferCellView")
@interface MultipleTransferCellView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework13NoAccountCard")
@interface NoAccountCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework23NotificationFilterModal")
@interface NotificationFilterModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC13AlatFramework11NumberField")
@interface NumberField : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework10OptionView")
@interface OptionView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, strong) IBInspectable UIImage * _Nullable optionIcon;
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic, copy) IBInspectable NSString * _Nullable descriptionText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull number;
@property (nonatomic) IBInspectable BOOL noImage;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11PaddedLabel")
@interface PaddedLabel : MediumLabel
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull background;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (void)drawTextInRect:(CGRect)rect;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13PasswordField")
@interface PasswordField : InputField
@end


SWIFT_CLASS("_TtC13AlatFramework16PastLoanCellView")
@interface PastLoanCellView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework17PendingActionView")
@interface PendingActionView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework22PendingTransactionView")
@interface PendingTransactionView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull title;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework10PhoneField")
@interface PhoneField : InputField
@end


SWIFT_CLASS("_TtC13AlatFramework11PickerModal")
@interface PickerModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end



@interface PickerModal (SWIFT_EXTENSION(AlatFramework)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC13AlatFramework8PinField")
@interface PinField : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11PlainButton")
@interface PlainButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

@class SemiLabel;

SWIFT_CLASS("_TtC13AlatFramework23PreApprovedLoanCellView")
@interface PreApprovedLoanCellView : BaseXib
@property (nonatomic, weak) IBOutlet SemiLabel * _Null_unspecified loanAmountLabel;
@property (nonatomic, weak) IBOutlet SemiLabel * _Null_unspecified tenorLabel;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19PreApprovedLoanView")
@interface PreApprovedLoanView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework21PrimaryBorderedButton")
@interface PrimaryBorderedButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13PrimaryButton")
@interface PrimaryButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework15QuickActionView")
@interface QuickActionView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework18RecipientListModal")
@interface RecipientListModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface RecipientListModal (SWIFT_EXTENSION(AlatFramework)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework12RegularLabel")
@interface RegularLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11SearchField")
@interface SearchField : InputField
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework17SegmentOptionView")
@interface SegmentOptionView : BaseXib
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified segmentImage;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic) IBInspectable BOOL isSelected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework31SegmentedOptionWithoutImageView")
@interface SegmentedOptionWithoutImageView : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nullable title;
@property (nonatomic) IBInspectable BOOL isSelected;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework14SelectableCard")
@interface SelectableCard : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)awakeFromNib;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework9SemiLabel")
@interface SemiLabel : CustomLabel
@property (nonatomic) IBInspectable CGFloat size;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework16SingleDetailView")
@interface SingleDetailView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13AlatFramework14SoftTokenModal")
@interface SoftTokenModal : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11SummaryView")
@interface SummaryView : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class NSTextStorage;

IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework13TextViewField")
@interface TextViewField : InputField <NSTextStorageDelegate>
- (void)textStorage:(NSTextStorage * _Nonnull)textStorage didProcessEditing:(NSTextStorageEditActions)editedMask range:(NSRange)editedRange changeInLength:(NSInteger)delta;
@end

@class NSLayoutManager;

@interface TextViewField (SWIFT_EXTENSION(AlatFramework)) <NSLayoutManagerDelegate>
- (CGFloat)layoutManager:(NSLayoutManager * _Nonnull)layoutManager lineSpacingAfterGlyphAtIndex:(NSInteger)glyphIndex withProposedLineFragmentRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13AlatFramework5Toast")
@interface Toast : UILabel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC13AlatFramework22TransactionHistoryCard")
@interface TransactionHistoryCard : BaseXib
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end








IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework12UploadButton")
@interface UploadButton : BaseXib
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull title;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull info;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull buttonText;
@property (nonatomic, copy) IBInspectable NSString * _Nonnull errorText;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)prepareForInterfaceBuilder;
@end

@class UIImagePickerController;
@class UIDocumentPickerViewController;
@class NSURL;

@interface UploadButton (SWIFT_EXTENSION(AlatFramework)) <UIDocumentPickerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
@end



IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework19WhiteBorderedButton")
@interface WhiteBorderedButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC13AlatFramework11WhiteButton")
@interface WhiteButton : UIButton
@property (nonatomic, copy) IBInspectable NSString * _Nonnull identifier;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end

#endif
#if defined(__cplusplus)
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
